### ISSUE TITLE
Helper nor reactive

### ISSUE THREAD

**Issue by Valentin-Seehausen** [vazco/meteor-universe-collection#1]
Hey, really great Package!

It makes MVC possible for Meteor which allows clean coding. Love it.

But: Could it be, that the helpers are not reactive? For example, when I load an instance in an view and change an attribute of the instance, the helper that is called in the view wont update. Clear enough description?

Regards,
Valentin

**Comment by Valentin-Seehausen** [comment]
Ah. Haha.

Seems to be the Collection Option transform, which you probably use. It wont be callbacked from changes in cursor or from observeChanges. http://docs.meteor.com/#/full/mongo_collection

Looking for a workaround...

**Comment by Valentin-Seehausen** [comment]
Er ... 

Ok, helpers are indeed reactive, I just made an mistake. Sorry.

Can be closed. 

-> Very great packages, though!

**Comment by cristo-rabani** [comment]
Hello Valentin,

If in helper will be something reactive then this helper will be a reactive source of data.
regular document isn't a reactive sorce of data.

 but you can make helper like:

```
var myDoc = UniCollection.UniDoc.extend();

myDoc.prototype.getMyReactiveField = function(){
       var doc = this.getCollection().findOne({_id: this._id}, {fields: {myReactiveField: 1}});
       return doc && doc.myReactiveField;
}

myColl.setConstructor(myDoc);
```

In future I going to make extension package to automatic creation reactive getters for selected fields of documents. 

Regards,
Cristo
