### ISSUE TITLE
Update readme and fix typos

### ISSUE THREAD

**Issue by skirunman** [vazco/meteor-universe-collection#10]
The readme file has a bunch of English typos and errors. It would help to understand this package if you could get someone to fix these typos. For example, the first sentence does not make much sense and could be rewritten as something like: "Universe Collections allows you to extend [Meteor Collections](http://docs.meteor.com/#/full/mongo_collection) by allowing you to define your own remote collection methods, add document helpers using a simple helpers method, and by creating new classes inherited from UniCollection.UniDoc." or something similar. Right now it is a bit hard to really understand what this package is trying to do from the introductory paragraph.

**Comment by cristo-rabani** [comment]
Hello, 
Thank you for remarks. 
Any other proposition of changes in the readme will be welcome.
