### ISSUE TITLE
UniCollection.publish and multiple mappings

### ISSUE THREAD

**Issue by radekmie** [vazco/meteor-universe-collection#11]
Hello.

I wanted to set multiple mappings, but, unfortunately, this code:

```
UniCollection.publish('users', function (query) {
    this.setMappings(Users, [
        {key: 'ownerId', reverse: true, collection: Blogs},
        {key: 'ownerId', reverse: true, collection: Posts}
    ]);

    return Users.find(query);
});
```

Sets only second mapping - next mapping with same `key` and `reverse` overwrites previous one.

**Comment by cristo-rabani** [comment]
Hello @radekmie 
Please check branch fix11. It should be fixed. So, if everything is well, let me know

**Comment by radekmie** [comment]
Yes, it's working.
