### ISSUE TITLE
Modernize package

### ISSUE THREAD

**Issue by skirunman** [vazco/meteor-universe-collection#24]
It would be great if this package could be modernized to:
1. Use new NPM version of [simple schema](https://github.com/aldeed/simple-schema-js) as old version is no longer supported and has not for well over a year. Because of this we have to use our [own custom version of simple schema](https://github.com/clozertech/meteor-simple-schema).
2. Remove dependency on Meteor underscore package. Meteor 1.6.2 has [removed underscore as a dependency on Meteor base](https://github.com/meteor/meteor/pull/9596) so this is dragging in a lot of unneeded code. Should move to Lodash and only depend on required functions (new version of simple schema does this).

**Comment by cristo-rabani** [comment]
Hello,
I added your suggestions as a proposition of task to the roadmap.
So, We will be discussed that on today tech meeting.

**Comment by skirunman** [comment]
Thanks, any update?

**Comment by cristo-rabani** [comment]
Hello, 
There is new version released, so please check it out. 
If there is more that can we change or improve let us know.

**Comment by skirunman** [comment]
@cristo-rabani  Thanks so much for the update. We have it on roadmap to do our upgrade too NPM version of Simple Schema and new version of Universe Collection.
