### ISSUE TITLE
Hooks on upsert

### ISSUE THREAD

**Issue by yurtsiv** [vazco/meteor-universe-collection#35]
When I do `upsert` which is actually `insert`, `update` hooks get's called.
I'm not sure it's the intended behaviour in this case. Or is it?

**Comment by radekmie** [comment]
@Natasza2476:
1. Set up an empty Meteor project.
2. Install this package and setup all possible hooks.
3. Check what hooks are triggered when an `upsert` happens (both for insert and update case).
4. Write down a summary here to decide how to proceed.

If neeed, all the code should be in [`lib/UniHooks.js`](https://github.com/vazco/meteor-universe-collection/blob/60b4d980f7026cc38b50066fbdff41ab66244fd5/lib/UniHooks.js).

**Comment by Natasza2476** [comment]
I created [test repository](https://github.com/Natasza2476/mu-test-repo) with checks of this behavoiur. What I found:
- `upsert` in insert case calls `update`,
- `upsert` in update case calls `update`.
Results in database look correct.

I guess that code responsible for that is in `lib/UniHooks.js`, as @radekmie told. Look at [line 110](https://github.com/vazco/meteor-universe-collection/blob/60b4d980f7026cc38b50066fbdff41ab66244fd5/lib/UniHooks.js#L110).

**Comment by Natasza2476** [comment]
According to (meteor/collection.js)[https://github.com/meteor/meteor/blob/c0ac59d6a038d24e63dd1d560b38ee87fe48262d/packages/mongo/collection.js#L640-L663] there is indeed `update` method called in `upsert`. It's called with parameter `upsert: true`, reffering to (db.collection.update())[https://docs.mongodb.com/manual/reference/method/db.collection.update/].

There is a workaround. Let us look on sample `arguments` when `upsert` is called:

[Arguments] {
  '1': { '$set': { title: 'New title' } },
  '0': { title: 'Old title' },
  '2': {
    _returnObject: true,
    upsert: true,
    generatedId: true,
    insertedId: 'n4qp3ai2yjLLk6jmH'
  },
  '3': undefined
}

In `update` hook you can check if `upsert` is set to `true`. Example code:

```
MyCollection.onBeforeCall('update', 'updateHookName', function(docToFind, docToChange){
  if(arguments[2].upsert){
    console.log('upsert');
    /* Do something with documents. */
  } else {
    console.log('update');
    /* Do something with documents. */
  }
});
```

If you want to make a PR with this issue, you're always welcome.
